version: "3.8"

services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}/flask-app:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - FLASK_ENV=production
    secrets:
      - flask_secret_key
    networks:
      - proxy

  proxy:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /srv/classproject/nginx/copper.steyaert.xyz.conf:/etc/nginx/conf.d/default.conf:ro
      - /srv/classproject/ssl:/etc/ssl/cloudflare:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - proxy

networks:
  proxy:
    driver: overlay
    attachable: true

secrets:
  flask_secret_key:
    external: true
