# This file is for building locally before deploying to swarm
# You must build and push the image before deploying:
#   docker build -t your-registry/flask-app:latest ./website
#   docker push your-registry/flask-app:latest
# Then update the image reference below and deploy with:
#   docker stack deploy -c docker-swarm.production.yml mystack

version: "3.8"

services:
  traefik:
    image: traefik:v3.2
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
      labels:
        - "traefik.enable=false"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      - TZ=America/New_York
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-config:/traefik.yml:ro
      - traefik-acme:/acme.json
      - traefik-dynamic:/dynamic:ro
    networks:
      - proxy

  web:
    # Update this to your registry/image:tag after building
    image: localhost:5000/flask-app:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.flask.entrypoints=http"
        - "traefik.http.routers.flask.rule=Host(`copper.steyaert.xyz`)"
        - "traefik.http.middlewares.flask-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.flask.middlewares=flask-https-redirect"
        - "traefik.http.routers.flask-secure.entrypoints=https"
        - "traefik.http.routers.flask-secure.rule=Host(`copper.steyaert.xyz`)"
        - "traefik.http.routers.flask-secure.tls=true"
        - "traefik.http.routers.flask-secure.tls.certresolver=cloudflare"
        - "traefik.http.routers.flask-secure.service=flask"
        - "traefik.http.services.flask.loadbalancer.server.port=8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-please-change-this-secret-key}
    networks:
      - proxy

volumes:
  traefik-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/traefik/traefik.yml
  traefik-acme:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/traefik/acme.json
  traefik-dynamic:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/traefik/dynamic

networks:
  proxy:
    driver: overlay
    attachable: true
