version: "3.8"

services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}/flask-app:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - FLASK_ENV=production
    secrets:
      - flask_secret_key
    networks:
      - proxy

  proxy:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /srv/classproject/nginx/copper.steyaert.xyz.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - certbot-webroot:/var/www/certbot:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - proxy

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    deploy:
      replicas: 0  # Only run manually or via cron
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none
    entrypoint: /bin/sh
    command: -c "certbot renew --webroot -w /var/www/certbot --quiet && nginx -s reload || true"

volumes:
  certbot-webroot:
    driver: local

networks:
  proxy:
    driver: overlay
    attachable: true

secrets:
  flask_secret_key:
    external: true
